// ─── CrowdSense — AI Chatbot Hook ────────────────────────────────────────────
// Powers the CrowdSense AI assistant. When VITE_GEMINI_API_KEY is present,
// responses are generated by Gemini 2.0 Flash. Otherwise, a smart local engine
// provides rule-based responses using real-time venue data. This ensures the
// chatbot always works — even without an internet connection.
// ─────────────────────────────────────────────────────────────────────────────
import { useState, useCallback } from 'react'
import type { ChatMessage } from '../types'
import { useAppStore } from '../store/useAppStore'
import { MOCK_ZONES, MOCK_GATES, MOCK_FOOD_COUNTERS, MOCK_MENU_ITEMS } from '../data/mockData'
import { generateGeminiResponse, isGeminiEnabled, type GeminiChatTurn } from '../lib/gemini'
import { CrowdSenseEvents } from '../lib/analytics'
import { logger } from '../lib/logger'

// ─── Constants ────────────────────────────────────────────────────────────────
const GREETING = `Hey there! 👋 I'm **CrowdSense AI** — your personal stadium assistant.

I can help you with:
• 🗺️ **Crowd levels** in different zones
• 🍔 **Food & drinks** recommendations
• 🚪 **Gate wait times** and best routes
• 🏆 **Your points** and tier status
• 📍 **Navigation** inside the stadium

What would you like to know?`

const SUGGESTIONS = [
  'How crowded is North Stand?',
  "What's the best food near me?",
  'My points balance',
  'Which gate has shortest wait?',
  'Show me veg food options',
  "What's my tier status?",
]

// ─── Message builders ─────────────────────────────────────────────────────────
function generateId(): string {
  return `msg_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`
}

function assistantMsg(content: string): ChatMessage {
  return { id: generateId(), role: 'assistant', content, timestamp: new Date().toISOString() }
}

function userMsg(content: string): ChatMessage {
  return { id: generateId(), role: 'user', content, timestamp: new Date().toISOString() }
}

// ─── Convert chat history to Gemini format ────────────────────────────────────
function toGeminiHistory(messages: ChatMessage[]): GeminiChatTurn[] {
  // Skip the greeting, take the last 10 turns, map roles
  return messages
    .slice(1)
    .slice(-10)
    .map(m => ({
      role:  m.role === 'user' ? 'user' : 'model',
      parts: [{ text: m.content }],
    } as GeminiChatTurn))
}

// ─── Mock response engine (fallback) ─────────────────────────────────────────
function buildZoneOverview(): string {
  const sorted    = [...MOCK_ZONES].sort((a, b) => a.occupancy - b.occupancy)
  const quietest  = sorted[0]
  const busiest   = sorted[sorted.length - 1]
  const avgPct    = Math.round(
    sorted.reduce((s, z) => s + (z.occupancy / z.capacity) * 100, 0) / sorted.length,
  )

  const lines = MOCK_ZONES.map(z => {
    const pct  = Math.round(z.occupancy / z.capacity * 100)
    const icon = z.level === 'low' ? '🟢' : z.level === 'medium' ? '🟡' : '🔴'
    return `${icon} ${z.name}: ${pct}%`
  })

  return `📊 **Stadium Overview** — ${avgPct}% average crowd density

🟢 **Quietest**: ${quietest.name} (${Math.round(quietest.occupancy / quietest.capacity * 100)}%)
🔴 **Busiest**:  ${busiest.name}  (${Math.round(busiest.occupancy / busiest.capacity * 100)}%)

${lines.join('\n')}

💡 I'd recommend heading to **${quietest.name}** for the best experience!`
}

type AppUser = ReturnType<typeof useAppStore.getState>['user']

/** Rule-based fallback response engine — always runs offline */
function generateMockResponse(text: string, user: AppUser): string {
  const q = text.toLowerCase()

  // ── Crowd / Zone ──
  if (/crowd|zone|stand|section|busy|packed/.test(q)) {
    const found = MOCK_ZONES.find(z =>
      q.includes(z.name.toLowerCase()) || q.includes(z.section.toLowerCase()),
    )
    if (found) {
      const pct   = Math.round((found.occupancy / found.capacity) * 100)
      const label = { low: 'comfortable', medium: 'moderate', high: 'crowded', full: 'packed' }[found.level]
      const icon  = { low: '🟢', medium: '🟡', high: '🔴', full: '🚨' }[found.level]
      const tip   = (found.level === 'high' || found.level === 'full')
        ? `\n\n💡 Try **${MOCK_ZONES.find(z => z.level === 'low')?.name ?? 'East Pavilion'}** — it's much emptier!`
        : ''
      return `${icon} **${found.name}** is **${label}** at ${pct}% capacity (${found.waitMinutes}m wait, ${found.trend})${tip}`
    }
    return buildZoneOverview()
  }

  // ── Gates ──
  if (/gate|entry|entrance|exit/.test(q)) {
    const found = MOCK_GATES.find(g => q.includes(g.name.toLowerCase()))
    if (found) {
      const icon = { open: '🟢', limited: '🟡', closed: '🔴' }[found.status]
      return `${icon} **${found.name}**: ${found.status}, ${found.waitMinutes}m wait${found.status === 'closed' ? '\n\n❌ This gate is closed — use a different one.' : ''}`
    }
    const open    = MOCK_GATES.filter(g => g.status === 'open')
    const fastest = [...open].sort((a, b) => a.waitMinutes - b.waitMinutes)[0]
    const rows    = MOCK_GATES.map(g => {
      const e = { open: '🟢', limited: '🟡', closed: '🔴' }[g.status]
      return `${e} **${g.name}**: ${g.waitMinutes}m${g.status === 'closed' ? ' (CLOSED)' : ''}`
    })
    return `🚪 **Gate Wait Times**\n\n${rows.join('\n')}\n\n✅ Fastest: **${fastest?.name}** — ${fastest?.waitMinutes}m wait`
  }

  // ── Food ──
  if (/food|eat|drink|burger|coffee|snack|hungry|veg|menu/.test(q)) {
    const isVeg = /veg|vegetarian/.test(q)
    const items = MOCK_MENU_ITEMS.filter(i => i.isAvailable && (!isVeg || i.isVeg)).slice(0, 5)
    if (items.length === 0) {
      return "😔 No items match your preference right now. Check the **Food** tab directly!"
    }
    const open    = MOCK_FOOD_COUNTERS.filter(c => c.isOpen)
    const fastest = [...open].sort((a, b) => a.waitMinutes - b.waitMinutes)[0]
    const rows    = items.map(i =>
      `${i.emoji} **${i.name}** ₹${(i.price / 100).toFixed(0)} ${i.isVeg ? '🌿' : ''}\n   ${i.counterName} · ⭐ ${i.rating}/5 · ~${i.preparationTime}m`,
    )
    return `${isVeg ? '🥗' : '🍔'} **${isVeg ? 'Veg Options' : 'Popular Items'}**\n\n${rows.join('\n\n')}\n\n🏪 ${open.length} counters open — lowest wait at **${fastest?.name}** (~${fastest?.waitMinutes}m)\n\n👉 Order in the **Food** tab!`
  }

  // ── Points / Tier ──
  if (/point|tier|reward|badge|level|xp|balance/.test(q)) {
    if (!user) return 'Please sign in to view your points balance!'
    const nextTier: Record<string, string> = {
      bronze: 'Silver (1,000 XP)', silver: 'Gold (2,500 XP)',
      gold: 'Platinum (5,000 XP)', platinum: 'Legend (10,000 XP)', legend: 'MAX TIER 👑',
    }
    const tierEmoji: Record<string, string> = {
      bronze: '🥉', silver: '🥈', gold: '🥇', platinum: '💎', legend: '👑',
    }
    return `🏆 **Your Status**

👤 ${user.displayName}
💰 Points: **${user.points.toLocaleString()}**
⚡ XP: **${user.xp.toLocaleString()}**
🎖️ Tier: **${user.tier}** ${tierEmoji[user.tier] ?? ''}

📈 Next: **${nextTier[user.tier]}**

Redeem at the **Profile** tab — 500pts for 10% off food!`
  }

  // ── Navigation ──
  if (/where|direction|navigate|find|restroom|toilet|bathroom|atm|cash/.test(q)) {
    if (/restroom|toilet|bathroom/.test(q)) {
      return `🚻 **Nearest Restrooms**\n\n• South Stand — Level 1, near Section B (🟢 Low queue)\n• East Pavilion — Near Gate 3\n• Main Concourse — Ground floor\n\n💡 South Stand is least crowded right now!`
    }
    if (/atm|cash/.test(q)) {
      return `🏧 **ATMs**\n\n• Main Gate lobby (SBI)\n• South Stand concourse (HDFC)\n• VIP entrance (ICICI)\n\nAll ATMs operational.`
    }
    return `🗺️ I can help you find restrooms, food counters, gates, ATMs, first aid, or parking. Try: *"Where's the nearest restroom?"*\n\nFor live navigation, check the **Map** tab!`
  }

  // ── Match ──
  if (/score|match|cricket|game|result/.test(q)) {
    return `🏏 **Live: Mumbai Indians vs Chennai Kings**\n\nMI: **168** | CSK: **142**\n\nWankhede Stadium · MI lead by 26 runs\n👥 32,480 fans attending`
  }

  // ── Greeting ──
  if (/hello|hi|hey|help/.test(q)) return GREETING

  // ── Default ──
  return `I can help with:\n\n🗺️ "How crowded is North Stand?"\n🍔 "Show me veg food"\n🚪 "Which gate has shortest wait?"\n🏆 "What's my points balance?"\n🏏 "Current score?"\n\nTry one of the suggestions below!`
}

// ─── Hook ─────────────────────────────────────────────────────────────────────
/**
 * Manages the AI chatbot state — messages, typing status, suggestions.
 * Uses Gemini AI when available, falls back to local mock engine.
 */
export function useChatBot() {
  const user = useAppStore(s => s.user)
  const activeZones = useAppStore(s => s.activeZones)

  const [messages, setMessages] = useState<ChatMessage[]>([assistantMsg(GREETING)])
  const [isTyping, setIsTyping]   = useState(false)

  const sendMessage = useCallback(async (text: string) => {
    if (!text.trim()) return

    // Add user message immediately
    const newUser = userMsg(text)
    setMessages(prev => {
      const next = [...prev, newUser]

      // Fire-and-forget the AI response after state update
      void (async () => {
        setIsTyping(true)

        try {
          let responseText: string | null = null

          if (isGeminiEnabled) {
            logger.debug('Sending message to Gemini AI')
            setMessages(prevMsgs => {
              const context = {
                zones:       activeZones.length > 0 ? activeZones : MOCK_ZONES,
                gates:       MOCK_GATES,
                counters:    MOCK_FOOD_COUNTERS,
                userTier:    user?.tier,
                userPoints:  user?.points,
                userName:    user?.displayName,
              }
              const history = toGeminiHistory(prevMsgs)
              void generateGeminiResponse(text, context, history).then(res => {
                responseText = res
              })
              return prevMsgs
            })

            // Wait for Gemini (max 8 seconds)
            const start = Date.now()
            while (responseText === null && Date.now() - start < 8000) {
              await new Promise(r => setTimeout(r, 100))
            }

            CrowdSenseEvents.chatMessageSent(responseText !== null ? 'ai' : 'mock')
          }

          // Fall back to mock if Gemini failed or is disabled
          if (responseText === null) {
            const delay = isGeminiEnabled ? 0 : 800 + Math.min(text.length * 3, 700)
            await new Promise(r => setTimeout(r, delay))
            responseText = generateMockResponse(text, user)
            if (!isGeminiEnabled) CrowdSenseEvents.chatMessageSent('mock')
          }

          setMessages(prev => [...prev, assistantMsg(responseText!)])
        } catch (err) {
          logger.warn('Chat response generation failed', err)
          setMessages(prev => [...prev, assistantMsg(generateMockResponse(text, user))])
        } finally {
          setIsTyping(false)
        }
      })()

      return next
    })
  }, [user, activeZones])

  const clearChat = useCallback(() => {
    setMessages([assistantMsg(GREETING)])
  }, [])

  return {
    messages,
    isTyping,
    suggestions: SUGGESTIONS,
    isAiMode:    isGeminiEnabled,
    sendMessage,
    clearChat,
  }
}
